// Mocks generated by Mockito 5.4.4 from annotations
// in sera_test/test/data/app_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sera_test/src/data/datasources/network/remote_data_source.dart'
    as _i5;
import 'package:sera_test/src/data/models/body/carts_body.dart' as _i13;
import 'package:sera_test/src/data/models/body/login_body.dart' as _i7;
import 'package:sera_test/src/data/models/body/product_body.dart' as _i11;
import 'package:sera_test/src/data/models/body/products_body.dart' as _i10;
import 'package:sera_test/src/data/models/body/users_body.dart' as _i9;
import 'package:sera_test/src/data/models/response/cart_response.dart' as _i12;
import 'package:sera_test/src/data/models/response/login_response.dart' as _i3;
import 'package:sera_test/src/data/models/response/product_response.dart'
    as _i4;
import 'package:sera_test/src/data/models/response/user_response.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductResponse_2 extends _i1.SmartFake
    implements _i4.ProductResponse {
  _FakeProductResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i5.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  _i6.Future<_i3.LoginResponse> login(_i7.LoginBody? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [body],
        ),
        returnValue: _i6.Future<_i3.LoginResponse>.value(_FakeLoginResponse_1(
          this,
          Invocation.method(
            #login,
            [body],
          ),
        )),
      ) as _i6.Future<_i3.LoginResponse>);

  @override
  _i6.Future<List<_i8.UserResponse>> users(_i9.UsersBody? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #users,
          [body],
        ),
        returnValue:
            _i6.Future<List<_i8.UserResponse>>.value(<_i8.UserResponse>[]),
      ) as _i6.Future<List<_i8.UserResponse>>);

  @override
  _i6.Future<List<_i4.ProductResponse>> products(_i10.ProductsBody? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #products,
          [body],
        ),
        returnValue: _i6.Future<List<_i4.ProductResponse>>.value(
            <_i4.ProductResponse>[]),
      ) as _i6.Future<List<_i4.ProductResponse>>);

  @override
  _i6.Future<_i4.ProductResponse> product(_i11.ProductBody? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #product,
          [body],
        ),
        returnValue:
            _i6.Future<_i4.ProductResponse>.value(_FakeProductResponse_2(
          this,
          Invocation.method(
            #product,
            [body],
          ),
        )),
      ) as _i6.Future<_i4.ProductResponse>);

  @override
  _i6.Future<List<_i12.CartResponse>> carts(_i13.CartsBody? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #carts,
          [body],
        ),
        returnValue:
            _i6.Future<List<_i12.CartResponse>>.value(<_i12.CartResponse>[]),
      ) as _i6.Future<List<_i12.CartResponse>>);
}
